language: php

jobs:
  include:
    - php: "5.3"
      dist: "precise"
    - php: "5.4"
      dist: "trusty"
    - php: "5.5"
      dist: "trusty"
    - php: "5.6"
      dist: "trusty"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit